### ISSUE TITLE
The url gives an error message.

### ISSUE THREAD

**Issue by suraj95** [cyberboysumanjay/Carbon-API#2]
Clicking on the API [link](https://carbonnowsh.herokuapp.com/ )

gives the following error message

`{"error":"Code is required to create a Carbon!"}`

**Comment by cyberboysumanjay** [comment]
Go through README Properly. 
If you won't specify the code which carbon has to beautify then how it will work?

Check example usage [here](https://carbonnowsh.herokuapp.com/?code=Made+with+Love+in+India+by+Sumanjay&theme=darcula&backgroundColor=rgba(144,%2019,%20254,%20100))

**Comment by suraj95** [comment]
Got it ! Thanks !
