### ISSUE TITLE
Add `pyppeteer-install` to instruction commands

### ISSUE THREAD

**Issue by cg-jl** [cyberboysumanjay/Carbon-API#3]
I followed the installation process to check your great project and tinker with it, but when running `python3 app.py` flask at first couldn't import `pyppeteer` :open_mouth: , which was rare at first because it was in the requirements file and thus installed by `pip` :thinking: . I went to the [pyppeteer pypi page](https://pypi.org/project/pyppeteer/) :page_with_curl:  and found that I had to run `pypeteer-install` so that pyppeteer had the drivers needed properly  installed on my system. After that, I re-run `python3 app.py` and all was up and running :+1: . I really appreciate your effort :heart: , as it is a tool that most of us want to have available. Keep up with the project! :100:

**Comment by cyberboysumanjay** [comment]
As per the Pyppeteer documentation
`Note: When you run pyppeteer for the first time, it downloads the latest version of Chromium (~150MB) if it is not found on your system. If you don't prefer this behaviour, ensure that a suitable Chrome binary is installed. One way to do this is to run pyppeteer-install command before prior to using this library.`

So it should not be an issue even if you don't install it prior to running this script.
