### ISSUE TITLE
One click heroku deployment fails

### ISSUE THREAD

**Issue by callmekatootie** [cyberboysumanjay/Carbon-API#5]
Received the following error when I tried to use the 1 click heroku deployment:

![carbon-api](https://user-images.githubusercontent.com/2317133/90365681-c9406680-e083-11ea-858f-4809d6853528.png)

**Comment by MysteryBots** [comment]
Same is happening with me. It's weird though as error message shows type worker when web is being used here. 
Did you solve it?

**Comment by callmekatootie** [comment]
No. I ended up using [Carbonara](https://github.com/petersolopov/carbonara) instead for my [Github Action](https://github.com/callmekatootie/carbonate)

**Comment by MysteryBots** [comment]
> No. I ended up using [Carbonara](https://github.com/petersolopov/carbonara) instead for my [Github Action](https://github.com/callmekatootie/carbonate)

Well I solved that. The problem was their is `worker` as process type in `app.json` while `web` in `Procfile`
Moreover this seems faster than the one about you said.
